export default function UrlManager() {
  return (
    <div className="space-y-6">
      <div className="card p-6">
        <h2 className="text-lg font-semibold text-gray-900 mb-2">URL List Manager</h2>
        <p className="text-sm text-gray-600">
          Maintain the BC and Blog URL lookup tables used by Flow 1. Add rows inline, upload a CSV,
          or paste a Google Sheets URL to import. Slugs are auto-generated by stripping the
          <code className="mx-1 px-1 bg-gray-100 rounded text-xs">https://www.brighton.co.id</code>
          domain from each URL.
        </p>
      </div>
      <div className="card p-12 flex flex-col items-center justify-center text-center border-dashed border-2">
        <div className="text-4xl mb-4">🚧</div>
        <div className="font-semibold text-gray-700 mb-1">Coming next</div>
        <div className="text-sm text-gray-500">
          Editable BC and Blog URL tables, CSV import, and Google Sheets import will be built next.
        </div>
      </div>
    </div>
  )
}
